# Generated by Django 4.1.7 on 2023-06-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0067_lead_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_work',
            name='target_count',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
