# Generated by Django 4.1.7 on 2023-06-23 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0068_daily_work_target_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_leeds_exists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('email_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ph_no', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('qualification', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('year_of_passout', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('collegename', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('internship', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('internship_institute', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('internship_topic', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('internship_start', models.DateField(blank=True, null=True)),
                ('internship_end', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('fresher_experience', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('previous_experience', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('register', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ex_duration', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('daily', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMcoreapp.daily_work')),
            ],
        ),
    ]
