# Generated by Django 4.1.7 on 2023-06-24 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0069_daily_leeds_exists'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_leeds_exists',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
