# Generated by Django 4.1.7 on 2023-06-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0070_daily_leeds_exists_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_leeds_exists',
            name='executive',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
